#define DECON_REINF_NONE 0
#define DECON_REINF_BULKHEAD_REMOVED 1
#define DECON_REINF_GRILLE_REMOVED 2
#define DECON_REINF_BRACING_REMOVED 3
#define DECON_REINF_BOLTS_UNDONE 4
#define DECON_NONE 0
#define DECON_WALL_WEAKENED 1

#define GIRDER_NOTHING "nothing"
#define GIRDER_STRUCTURAL "structural"
#define GIRDER_PLATED "plated"

#define STRUCTURE_COST 2
#define PLATING_COST 2
#define REINFORCEMENT_COST 2

#define WALL_DECON_STEP_TIME 2 SECONDS
#define WALL_DECON_STEP_REINF_TIME 5 SECONDS
